### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by DarkerInker**
I really am not sure what the hell you were doing in your Index.js File...

```js
let rawdata = fs.readFileSync('config.json');
let data = JSON.parse(rawdata);
```
What the fuck is this?? you can legit do the same thing just doing

```js
let config = require("./config.json")
let username = config.username;
```
Have you ever used Nodejs???

### CODE REVIEW

**Comment by krushna06** [comment]
> I really am not sure what the hell you were doing in your Index.js File...
> 
> ```js
> let rawdata = fs.readFileSync('config.json');
> let data = JSON.parse(rawdata);
> ```
> 
> What the fuck is this?? you can legit do the same thing just doing
> 
> ```js
> let config = require("./config.json")
> let username = config.username;
> ```
> 
> Have you ever used Nodejs???

If you even know the basics of nodejs then you will understand, the bot needs to join the aternos server and the ip is in config.json file, so the bot will find the ip from config file, then the username that the bot will use, it will be used from the config file. Thats what the code means that you highlighted. The main purpose of this was too make it work and as long as its working idc what others say.

**Comment by DarkerInker** [comment]
> > I really am not sure what the hell you were doing in your Index.js File...
> > ```js
> > let rawdata = fs.readFileSync('config.json');
> > let data = JSON.parse(rawdata);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What the fuck is this?? you can legit do the same thing just doing
> > ```js
> > let config = require("./config.json")
> > let username = config.username;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Have you ever used Nodejs???
> 
> If you even know the basics of nodejs then you will understand, the bot needs to join the aternos server and the ip is in config.json file, so the bot will find the ip from config file, then the username that the bot will use, it will be used from the config file. Thats what the code means that you highlighted. The main purpose of this was too make it work and as long as its working idc what others say.

dude you are using useless things while you could use PLAIN NODEJS to get stuff from JSON files you don't need to parse it for 0 reason. Its pointless

**Comment by krushna06** [comment]
> > > I really am not sure what the hell you were doing in your Index.js File...
> > > ```js
> > > let rawdata = fs.readFileSync('config.json');
> > > let data = JSON.parse(rawdata);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > What the fuck is this?? you can legit do the same thing just doing
> > > ```js
> > > let config = require("./config.json")
> > > let username = config.username;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Have you ever used Nodejs???
> > 
> > 
> > If you even know the basics of nodejs then you will understand, the bot needs to join the aternos server and the ip is in config.json file, so the bot will find the ip from config file, then the username that the bot will use, it will be used from the config file. Thats what the code means that you highlighted. The main purpose of this was too make it work and as long as its working idc what others say.
> 
> dude you are using useless things while you could use PLAIN NODEJS to get stuff from JSON files you don't need to parse it for 0 reason. Its pointless

Still works*

**Comment by DarkerInker** [comment]
> > > > I really am not sure what the hell you were doing in your Index.js File...
> > > > ```js
> > > > let rawdata = fs.readFileSync('config.json');
> > > > let data = JSON.parse(rawdata);
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > What the fuck is this?? you can legit do the same thing just doing
> > > > ```js
> > > > let config = require("./config.json")
> > > > let username = config.username;
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Have you ever used Nodejs???
> > > 
> > > 
> > > If you even know the basics of NodeJS then you will understand, the bot needs to join the aternos server and the IP is in the config.json file, so the bot will find the IP from the config file, then the username that the bot will use, it will be used from the config file. That's what the code means that you highlighted. The main purpose of this was to make it work and as long as it's working idc what others say.
> > 
> > 
> > dude you are using useless things while you could use PLAIN NODEJS to get stuff from JSON files you don't need to parse it for 0 reasons. It's pointless
> 
> Still works like a charm*

But it's pointless and more work just to get something from a JSON file. You could use two lines of code to get something from a config file instead of three...

```js
const config = require("./config.json")
console.log(config.item)
```

compared to your way
```js
let rawdata = fs.readFileSync('config.json');
let data = JSON.parse(rawdata);
console.log(data["item"])

**Comment by krushna06** [comment]
> > > > > I really am not sure what the hell you were doing in your Index.js File...
> > > > > ```js
> > > > > let rawdata = fs.readFileSync('config.json');
> > > > > let data = JSON.parse(rawdata);
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > What the fuck is this?? you can legit do the same thing just doing
> > > > > ```js
> > > > > let config = require("./config.json")
> > > > > let username = config.username;
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Have you ever used Nodejs???
> > > > 
> > > > 
> > > > If you even know the basics of NodeJS then you will understand, the bot needs to join the aternos server and the IP is in the config.json file, so the bot will find the IP from the config file, then the username that the bot will use, it will be used from the config file. That's what the code means that you highlighted. The main purpose of this was to make it work and as long as it's working idc what others say.
> > > 
> > > 
> > > dude you are using useless things while you could use PLAIN NODEJS to get stuff from JSON files you don't need to parse it for 0 reasons. It's pointless
> > 
> > 
> > Still works like a charm*
> 
> But it's pointless and more work just to get something from a JSON file. You could use two lines of code to get something from a config file instead of three...
> 
> ```js
> const config = require("./config.json")
> console.log(config.item)
> ```
> 
> compared to your way
> 
> ```js
> let rawdata = fs.readFileSync('config.json');
> let data = JSON.parse(rawdata);
> console.log(data["item"])
> ```

Does anyone care...? People just want it working.

**Comment by DarkerInker** [comment]
> > > > > > I really am not sure what the hell you were doing in your Index.js File...
> > > > > > ```js
> > > > > > let rawdata = fs.readFileSync('config.json');
> > > > > > let data = JSON.parse(rawdata);
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > What the fuck is this?? you can legit do the same thing just doing
> > > > > > ```js
> > > > > > let config = require("./config.json")
> > > > > > let username = config.username;
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > Have you ever used Nodejs???
> > > > > 
> > > > > 
> > > > > If you even know the basics of NodeJS then you will understand, the bot needs to join the aternos server and the IP is in the config.json file, so the bot will find the IP from the config file, then the username that the bot will use, it will be used from the config file. That's what the code means that you highlighted. The main purpose of this was to make it work and as long as it's working idc what others say.
> > > > 
> > > > 
> > > > dude you are using useless things while you could use PLAIN NODEJS to get stuff from JSON files you don't need to parse it for 0 reasons. It's pointless
> > > 
> > > 
> > > Still works like a charm*
> > 
> > 
> > But it's pointless and more work just to get something from a JSON file. You could use two lines of code to get something from a config file instead of three...
> > ```js
> > const config = require("./config.json")
> > console.log(config.item)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > compared to your way
> > ```js
> > let rawdata = fs.readFileSync('config.json');
> > let data = JSON.parse(rawdata);
> > console.log(data["item"])
> > ```
> 
> Does anyone care...? People just want it working.

The point is you are doing useless things using more ram than needed... Who the fuck parses a JSON file when you can use two lines to get something from it? It just seems pointless

**Comment by krushna06** [comment]
> > > > > > > I really am not sure what the hell you were doing in your Index.js File...
> > > > > > > ```js
> > > > > > > let rawdata = fs.readFileSync('config.json');
> > > > > > > let data = JSON.parse(rawdata);
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > What the fuck is this?? you can legit do the same thing just doing
> > > > > > > ```js
> > > > > > > let config = require("./config.json")
> > > > > > > let username = config.username;
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > Have you ever used Nodejs???
> > > > > > 
> > > > > > 
> > > > > > If you even know the basics of NodeJS then you will understand, the bot needs to join the aternos server and the IP is in the config.json file, so the bot will find the IP from the config file, then the username that the bot will use, it will be used from the config file. That's what the code means that you highlighted. The main purpose of this was to make it work and as long as it's working idc what others say.
> > > > > 
> > > > > 
> > > > > dude you are using useless things while you could use PLAIN NODEJS to get stuff from JSON files you don't need to parse it for 0 reasons. It's pointless
> > > > 
> > > > 
> > > > Still works like a charm*
> > > 
> > > 
> > > But it's pointless and more work just to get something from a JSON file. You could use two lines of code to get something from a config file instead of three...
> > > ```js
> > > const config = require("./config.json")
> > > console.log(config.item)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > compared to your way
> > > ```js
> > > let rawdata = fs.readFileSync('config.json');
> > > let data = JSON.parse(rawdata);
> > > console.log(data["item"])
> > > ```
> > 
> > 
> > Does anyone care...? People just want it working.
> 
> The point is you are doing useless things using more ram than needed... Who the fuck parses a JSON file when you can use two lines to get something from it? It just seems pointless

Man, you are just wasting my time and your time cause this isn't getting me anywhere. This doesn't create any problem nor does it give any solution so just shut your dumb ass mouth and close the thread or I will do it.

**Comment by wutv** [comment]
> > > > > > > I really am not sure what the hell you were doing in your Index.js File...
> > > > > > > ```js
> > > > > > > let rawdata = fs.readFileSync('config.json');
> > > > > > > let data = JSON.parse(rawdata);
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > What the fuck is this?? you can legit do the same thing just doing
> > > > > > > ```js
> > > > > > > let config = require("./config.json")
> > > > > > > let username = config.username;
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > Have you ever used Nodejs???
> > > > > > 
> > > > > > 
> > > > > > If you even know the basics of NodeJS then you will understand, the bot needs to join the aternos server and the IP is in the config.json file, so the bot will find the IP from the config file, then the username that the bot will use, it will be used from the config file. That's what the code means that you highlighted. The main purpose of this was to make it work and as long as it's working idc what others say.
> > > > > 
> > > > > 
> > > > > dude you are using useless things while you could use PLAIN NODEJS to get stuff from JSON files you don't need to parse it for 0 reasons. It's pointless
> > > > 
> > > > 
> > > > Still works like a charm*
> > > 
> > > 
> > > But it's pointless and more work just to get something from a JSON file. You could use two lines of code to get something from a config file instead of three...
> > > ```js
> > > const config = require("./config.json")
> > > console.log(config.item)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > compared to your way
> > > ```js
> > > let rawdata = fs.readFileSync('config.json');
> > > let data = JSON.parse(rawdata);
> > > console.log(data["item"])
> > > ```
> > 
> > 
> > Does anyone care...? People just want it working.
> 
> The point is you are doing useless things using more ram than needed... Who the fuck parses a JSON file when you can use two lines to get something from it? It just seems pointless

Require caches JSON output. fs.readFileSync and JSON.parse would be better.

**Pull request closed without merging**
